version: "2.4"

services:
  db:
    container_name: ${PROJECT_NAME:-openimis}-db
    build:
      context: https://github.com/openimis/database_postgresql.git#${DB_BRANCH:-develop}
      args:
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
    networks:
      openimis-net:
  backend:
    container_name: ${PROJECT_NAME:-openimis}-api
    image: ghcr.io/openimis/openimis-be:${DB_BRANCH:-develop}
    command: start
    environment: &backend-env
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SITE_ROOT=api
      - DEBUG=True
      - DJANGO_LOG_LEVEL=DEBUG
      - SITE_URL=${NEW_OPENIMIS_HOST}
      - CELERY_BROKER_URL=amqp://rabbitmq
    depends_on:  
      db:
        condition: service_healthy
    networks:
      openimis-net:

  frontend:
    container_name: ${PROJECT_NAME:-openimis}-frontend
    image: ghcr.io/openimis/openimis-fe:${FE_BRANCH:-develop}
    environment:
      - REACT_APP_API_URL=api
      - NEW_OPENIMIS_HOST=${NEW_OPENIMIS_HOST}
      - OPENIMIS_CONF_JSON=${OPENIMIS_FE_CONF_JSON}
    networks:
      openimis-net:
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    depends_on:
      - backend

  worker:
    container_name: ${PROJECT_NAME:-openimis}-worker
    image: ghcr.io/openimis/openimis-be:${BE_BRANCH:-develop}
    command: worker
    restart: always
    depends_on: 
      - backend
    environment: *backend-env
    networks:
      openimis-net:
  rabbitmq:
    container_name: ${PROJECT_NAME:-openimis}-rabbitmq
    image: rabbitmq:3-management
    restart: always
    networks:
      openimis-net:
  restapi:
    container_name: ${PROJECT_NAME:-openimis}-restapi
    image: ghcr.io/openimis/openimis-rest_api:${RESTAPI_BRANCH:-develop}
    volumes:
      - ./conf/restapi:/app/config
      - ./logs:/app/log
    restart: always
    depends_on:  
      db:
        condition: service_healthy
    networks:
      openimis-net:
networks:
  openimis-net:
volumes:
  database: