version: "2.4"

services:
  db:
    container_name: ${PROJECT_NAME:-openimis}-db
    build:
      context: https://github.com/openimis/database_ms_sqlserver.git#${DB_BRANCH:-develop} 
      args:
        - ACCEPT_EULA=${ACCEPT_EULA}
        - SA_PASSWORD=${DB_PASSWORD}
    environment:
      - DB_USER_PASSWORD=${DB_PASSWORD}
      - SA_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - ACCEPT_EULA=${ACCEPT_EULA}
    healthcheck:
      test: "bash /app/healthcheck.sh"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 100s
    networks:
      openimis-net:
    volumes:
      - database:/var/opt/mssql/data
    ports:
      - 1433:1433
  ## WARNING:
    ## exposing the database port outside the openimis-net network
    ## may lead to security issue (depending on your network topology)
    # ports:
    #  - 1433:1433
  backend:
    container_name: ${PROJECT_NAME:-openimis}-api
    image: ghcr.io/openimis/openimis-be:${BE_BRANCH:-develop}
    command: start
    volumes:
      - photos:/openimis-be/openIMIS/images/insurees
    environment: &backend-env
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SITE_ROOT=api
      - DEBUG=True
      - DJANGO_LOG_LEVEL=DEBUG
      - SITE_URL=${NEW_OPENIMIS_HOST}
      - CELERY_BROKER_URL=amqp://rabbitmq
    depends_on:  
      db:
        condition: service_healthy
    networks:
      openimis-net:

  gateway:
    container_name: ${PROJECT_NAME:-openimis}-frontend
    image: ghcr.io/openimis/openimis-fe:${FE_BRANCH:-develop}
    environment:
      - REACT_APP_API_URL=api
      - NEW_OPENIMIS_HOST=${NEW_OPENIMIS_HOST}
      - OPENIMIS_CONF_JSON=${OPENIMIS_FE_CONF_JSON}
    networks:
      openimis-net:
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    depends_on:
      - backend
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  worker:
    container_name: ${PROJECT_NAME:-openimis}-${BE_BRANCH:-develop}
    image: ghcr.io/openimis/openimis-be:develop
    command: worker
    restart: always
    volumes:
      - photos:/openimis-be/openIMIS/images/insurees
    depends_on: 
      - backend
    environment: *backend-env
    networks:
      openimis-net:
  rabbitmq:
    container_name: ${PROJECT_NAME:-openimis}-rabbitmq
    image: rabbitmq:3-management
    restart: always
    networks:
      openimis-net:
  restapi:
    container_name: ${PROJECT_NAME:-openimis}-restapi
    image: ghcr.io/openimis/openimis-rest_api:${RESTAPI_BRANCH:-develop}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      #- ./conf/restapi:/app/config
      - ./logs:/app/log
      - photos:/app/photos
      - ./Escape:/app/Escape
      - ./FromPhone:/app/FromPhone
    restart: always
    depends_on:  
      db:
        condition: service_healthy
    networks:
      openimis-net:
networks:
  openimis-net:
volumes:
  database:
  photos:
